[colors.primary]
background = '#0e1514'
foreground = '#dde4e2'

[colors.selection]
text = '#dde4e2'
background = '#005049'

[colors.cursor]
text = '#0e1514'
cursor = '#81d5ca'

[colors.normal]
black   = '#0e1514'
red     = '#f49c6e'
green   = '#6ad571'
yellow  = '#fff372'
blue    = '#6acabd'
magenta = '#1b6259'
cyan    = '#81d5ca'
white   = '#d2dfdd'

[colors.bright]
black   = '#808a89'
red     = '#ffc09f'
green   = '#a5ffab'
yellow  = '#fff7a5'
blue    = '#9beae0'
magenta = '#b8fff5'
cyan    = '#d1fff9'
white   = '#f8fffe'
